#!/bin/sh

set -eu

# The following environment variables can be overridden by ~/.config/myvm or ~/.myvm
DISK_DIR="/var/isos"
ROOT_PASS="pass1234"
USER_NAME="user" USER_FULL_NAME="User" USER_PASS="pass1234"
DEFAULT_TIMEOUT=60

version() { echo "0.0.1"; }
usage() {
  cat <<HERE
Usage: myvm <command> <shrc-file> [<args>]...

commands:
  run <shrc-file> [<tasks> | --step-on]...
  sendkey <shrc-file> [<keys>]...
  ocr <shrc-file>
  vnc <shrc-file> [enable | disable | display]
  demolish <shrc-file>
HERE
}

abort() {
  [ $# -gt 0 ] && echo "$1" >&2
  exit 1
}

if (export PATH=/dev/null; shopt -s expand_aliases 2>/dev/null); then
  shopt -s expand_aliases
fi

for i in stop restart setmem vnc attach_disk detach_disk; do
  eval "alias vm.$i='vm_$i \"\$DOMAIN\"'"
done
. ./lib/vm.sh

exalias() {
  if (eval "function '$1'() { :; }") >/dev/null 2>&1; then
    eval "function '$1'() { $2 \"\$@\"; }"
  elif (alias "$1=:") 2>/dev/null; then
    alias "$1=$2"
  else
    alias -- "$1=$2"
  fi
}

step_mode=false
step_on() {
  step_mode=true
}

sendkey() {
  [ $# -eq 0 ] && return 0
  if $step_mode; then
    while true; do
      printf '%s' "Send keys: $* ? [Y/s/a/o or ? for help]: "
      read -r REPLY
      case ${REPLY:-y} in
        [yY]*) break ;;
        [sS]*) return 0 ;;
        [aA]*) step_mode=false && break ;;
        [oO]*) ocr ;;
        '?'*) echo "Help: [Y]es / [S]kip / Yes to [A]ll / [O]CR" ;;
      esac
    done
  else
    echo "Send keys: $*"
  fi

  vm_sendkey "$DOMAIN" "$@"
}

enter() {
  IFS=" $IFS" && set -- "$*" && IFS="${IFS#?}"
  case $1 in
    '{'*'}') sendkey "$1" '{' "${1#?}" '{ENTER}' ;;
    *) sendkey "$1" '{ENTER}'
  esac
}

prompt() {
  waitfor "$1"
  shift
  sendkey "$@"
}

next_timeout=''
timeout() {
  set -- "$1" "${2:-"Time-consuming"}"
  next_timeout="$1"
  echo "$2 process in progress (extend the next timeout to $1 seconds)"
}

waitfor() {
  set -- "$1" "${2:-}" "${next_timeout:-$DEFAULT_TIMEOUT}"
  next_timeout=''

  set -- "$1" "$2" "$3" 10
  [ "$3" -le 300 ] && set -- "$1" "$2" "$3" 5
  [ "$3" -le 60 ] && set -- "$1" "$2" "$3" 3

  printf '%s' "Waiting for '$1' "
  start=$(date +%s) && end=$start
  while [ "$end" -le $((start + $3)) ]; do
    printf '.'
    if texts=$(ocr); then
      [ "$2" ] && _match "$texts" "$2" && echo " [Failure]" && return 1
      _match "$texts" "$1" && echo " [Found]" && return 0
    else
      echo " [Error]" && return 1
    fi
    sleep "$4"
    end=$(date +%s)
  done
  echo " [Timeout]"
  return 1
}

_match() {
  (
    set -f && IFS="*"
    set -- "$(_join "$1")" $(_join "$2")
    i=1 pattern=''
    while [ "$i" -lt $# ] && i=$((i + 1)); do
      pattern="${pattern}${pattern:+"*"}\"\$$i\""
    done
    eval "case \$1 in (*$pattern*) exit 0; esac"
    exit 1
  )
}

_join() {
  printf '%s' "$1" | tr -s '\n' ' '
}

exalias - enter

begin_shell() {
  echo "exec shell: $1"
  enter "sh << 'MYVM_SHELL_HEREDOC'"
  enter "set -- '$1'"
  enter "( set -e"
}

end_shell() {
  enter ')'
  enter "e=\$? s=success && [ \$e -eq 0 ] || s=failure"
  enter "echo \$1 \$s \$e"
  enter 'MYVM_SHELL_HEREDOC'
}

begin_file() {
  enter "cat << 'MYVM_FILE_HEREDOC' > $1"
}

end_file() {
  enter 'MYVM_FILE_HEREDOC'
}

copy_file() {
  enter "mkdir -p ${2%/*}"
  enter "cat << 'MYVM_FILE_HEREDOC' > $2"
  while IFS= read -r line; do
    enter "$line"
  done < "$1"
  enter 'MYVM_FILE_HEREDOC'
}

spelling_correction() {
  cat
}

exec_ocr() {
  gm convert - -colorspace Gray -resize 200% - | tesseract --psm 6 - -
}

ocr() {
  vm_screenshot "$DOMAIN" | exec_ocr | {
    LANG=C tr -cs '[:print:]\n' ' ' | grep .
  } | spelling_correction
}

cmd_run() {
  for i in "$@"; do
    case $i in
      --step-on) continue ;;
      *[!0-9a-zA-Z_]*) abort "Invalid task name '$i'" ;;
    esac
    eval "do_$i() { abort \"Task '$i' not defined\"; }"
  done

  . "$SHRC"

  for i in "$@"; do
    [ "$i" = '--step-on' ] && step_on && continue
    "do_${i}"
  done
}

cmd_sendkey() {
  sendkey "$@"
}

cmd_ocr() {
  . "$SHRC"
  ocr
}

cmd_vnc() {
  vm_vnc "$DOMAIN" "$@"
}

cmd_demolish() {
  while true; do
    printf "Enter a domain name to delete a virtual machine: "
    read -r REPLY
    [ "$REPLY" = "" ] && echo "Nothing done." && return 1
    [ "$REPLY" = "$DOMAIN" ] || continue
    vm_demolish "$DOMAIN"
    break
  done
}

case ${1:-} in
  run | sendkey | ocr | vnc | demolish) SUBCOMMAND=$1 ;;
  -h | --help | help) usage && exit 0 ;;
  -V | --version | version) version && exit 0 ;;
  *) echo "Invalid subcommand." && usage && abort ;;
esac
shift

case ${1:-} in
  *.shrc) [ ! -e "$1" ] && abort "The specified shrc file does not exist." ;;
  '') abort "Please specify the shrc file." ;;
  *) abort "The file extension must be .shrc." ;;
esac

SHRC=$1
DOMAIN="${1%/*}${1#*/}" && DOMAIN=${DOMAIN%.shrc}
HOSTNAME="$(echo "$DOMAIN" | tr . -)"
shift

for i in "./myvmrc" "$HOME/.myvmrc" "$HOME/.config/myvmrc"; do
  [ -f "$i" ] || continue
  echo "Configuration file loaded from $i."
  . "$i"
done
echo "myvm (Domain: $DOMAIN, Hostname: $HOSTNAME)"
echo

# The following braces make it safe to modify the script during execution
{
  [ "$SUBCOMMAND" = "run" ] && trap 'abort Aborted.' EXIT
  "cmd_${SUBCOMMAND}" "$@"
  trap - EXIT
  exit 0
}
